config/routes.rb
Rails.application.routes.draw do
  get '/feed', to: 'feed#index'

  devise_for :users

  resources :users do
    resources :items
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  get '/', to: 'home#index'

  get '/about', to: 'home#about'

  get '/contact', to: 'home#contact'

  root 'home#index'
  get '/search', to: 'items#search'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  default_scope { order 'created_at DESC' }
  validates :name, presence: true
  validates :image, presence: true
  validates :description, presence: true, length: { minimum: 6 }

  mount_uploader :image, ItemImageUploader

  def self.search(search)
      where('lower(name) LIKE ? OR lower(description) LIKE ? OR lower(store) LIKE ?', "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%")
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/support/utilities.rb
def full_title(page_title)
  base_title = "Ruby on Rails Tutorial Sample App"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
end

def sign_in(user, options={})
  if options[:no_capybara]
    # Sign in when not using Capybara.
    remember_token = User.new_remember_token
    cookies[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
  else
    visit signin_path
    fill_in "Email",    with: user.email
    fill_in "Password", with: user.password
    click_button "Sign in"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { username.downcase }
  has_many :items, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username,
            presence: true,
            length: { minimum: 4 },
            uniqueness: { case_sensitive: false }

  mount_uploader :image, ProfilePictureUploader

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :image, :password, :email) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :image, :password, :email, :current_password) }

  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def index
    @items = Item.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @user = current_user
      @items = @user.items
    end
  end

  def about
  end

  def contact
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def new
  end

  def create
    @user = User.find(params[:user_id])
    if @item = @user.items.create(item_params)
      redirect_to root_path
    else
      render root_path
    end
  end

  def show
    @user = User.find(params[:user_id])
    @item = @user.items.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    @user = User.find(params[:user_id])
    @item = @user.items.find(params[:id])
    @item.destroy
    redirect_to root_path
  end

  def search
    @items = Item.search(params[:search])
  end

  private

    def item_params
      params.require(:item).permit(:name, :description, :image, :store)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.all
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.all
    render 'show_follow'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page)
    if page.blank?
      "Looks"
    else
      "Looks | #{page}"
    end
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feed/index.html.erb
<% provide(:title, "Feed") %>
<ul>
  <%= render @items %>
</ul>

app/views/home/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>

<p>
  Looks is an app I created to brag about new stuff you bought. 
</p>

app/views/home/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>

<p>
  You can contact me a <a href="mailto:mattreed1890@gmail.com">mattreed1890@gmail.com</a>. 
</p>

app/views/home/index.html.erb
<% provide(:title, " ") %>
<% if user_signed_in? %>

	<div class="user-area">
		<h2><%= @user.username %></h2>
		<%= image_tag @user.image.url(:medium) %>
		<%= render 'items/form' %>
		<p><%= link_to "Edit profile", edit_user_registration_path %></p>
	</div>
	<div class="item-area">
		<% if @items.count == 0 %>
			<h2>You have no items!</h2>
		<% else %>
			<h2>You have <%= pluralize(@items.count, "item") %>.</h2>
			<ul>
				<%= render @items %>
			</ul>
		<% end %>
	</div>

<% else %>
<div class="hero">
	<div class="hero-inner">
    <a href="" class="hero-logo"><img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt=""></a>
		<div class="hero-copy">
			<h1>Looks</h1>
			<p>Looks is the best way to brag about the awesome outfit you just bought!</p>
		</div>
    <button><%= link_to "Sign Up", new_user_registration_path %></button>
	</div>
</div>
<div class="bullets">
  <div class="bullet three-col-bullet">
    <div class="bullet-icon bullet-icon-1">
      <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_2.png" alt="">
    </div>
    <div class="bullet-content">
      <h2>This Bullet Title</h2>
      <p>Lorem dolor sit amet consectetur adipisicing elit. Doloremque, minus, blanditiis, voluptatibus nulla quia ipsam sequi quos iusto aliquam iste magnam accusamus molestias quo illum impedit. Odit officia autem.</p>
      </div>
  </div>
  <div class="bullet three-col-bullet">
    <div class="bullet-icon bullet-icon-2">
      <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_3.png" alt="">
    </div>
    <div class="bullet-content">
      <h2>Another Bullet Title</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque, minus, blanditiis, voluptatibus nulla quia ipsam sequi quos iusto aliquam iste magnam accusamus molestias quo illum.</p>
    </div>
  </div>
  <div class="bullet three-col-bullet">
    <div class="bullet-icon bullet-icon-3">
      <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_4.png" alt="">
    </div>
    <div class="bullet-content">
      <h2>Last Bullet Title</h2>
      <p>Lorem ipsum sit amet consectetur adipisicing elit. Doloremque, minus, blanditiis, voluptatibus nulla quia ipsam sequi quos iusto aliquam iste magnam accusamus molestias quo illum impedit. Odit officia autem.</p>
    </div>
  </div>
</div>
<% end %>

app/views/items/_form.html.erb
<%= form_for([@user, Item.new], html: { multipart: true } ) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :store %>
  <%= f.text_field :store %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit "Add Item" %>

<% end %>

app/views/items/_item.html.erb
<li class="item">
  <%= link_to([item.user, item]) do %>
    <%= image_tag item.image_url(:medium), id: "item_image" %>
    <div class="hover">
      <h4><%= item.name %></h4>
      <p>
        <%= item.description %>
      </p>

    </div>
  <% end %>
</li>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/search.html.erb
<% provide(:title, "Search") %>
<ul>
  <%= render @items %>
</ul>

app/views/items/show.html.erb
<%= provide(:title, @item.name) %>

<div class="item">
  <h1><%= @item.name %></h1>
  <h3><%= @item.store %></h3>
  <%= image_tag @item.image.url%>
  <p>
    <%= @item.description %>
  </p>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer-logo">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
  </div>
  <div class="footer-links">
    <ul>
      <li><h3>Links</h3></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Blog", "#" %></li>
    </ul>
    <ul>
      <li><h3>Follow Us</h3></li>
      <li><%= link_to "Facebook", "#" %></li>
      <li><%= link_to "Twitter", "#" %></li>
      <li><%= link_to "Youtube", "#" %></li>
    </ul>
    <ul>
      <li><h3>Legal</h3></li>
      <li><%= link_to "Terms and Conditions", "#" %></li>
      <li><%= link_to "Privacy Policy", "#" %></li>
    </ul>
  </div>

  <hr>

  <p>&copy;<%= Time.now.year %> Looks. By: <%= link_to "Matt Reed", "http://mttrd.com" %></p>
</footer>

app/views/layouts/_header.html.erb
<header class="navigation">
  <div class="menu-wrapper">
    <%= link_to "#{image_tag('https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png')}".html_safe, root_path, class: "logo" %>
      <%=  %>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
      <ul id="navigation-menu">
        <li><%= link_to 'Feed', feed_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <li class="navigation-search-bar">
          <div class="search-bar">
            <div class="search-and-submit">
              <%= form_tag(search_path, method: "get") do %>
                <%= search_field_tag :search, params[:search] %>
                <%= button_tag "#{image_tag "https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon.png"}".html_safe , type: "submit" %>
              <% end %>
            </div>
          </div>
        </li>
        <% if user_signed_in? %>
          <li class="sign-up"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="sign-up"><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="grid">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<ul>
  <% @users.each do |user| %>
    <%= link_to user do %>
    <li class="block"><%= image_tag user.image.url(:medium) %></li>
    <% end %>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= provide(:title, @user.username) %>

<h1><%= @user.username %></h1>
<%= image_tag @user.image.url(:medium) %>
<%= render @user.items %>
<% if @user == current_user %>
  <%= link_to "Edit profile", edit_user_registration_path(@user) %>
<% end %>
<section>
  <%= render 'shared/stats' %>
  <%= render 'follow_form' if signed_in? %>
</section>

app/views/users/show_follow.html.erb
<% @users.each do |user| %>
  <%= link_to image_tag(user.image.url(:medium)), user %>
<% end %>